// REGISTRATION FORM CONSTANTS
export const ACTIVE_STEP_INCREMENT = "ACTIVE_STEP_INCREMENT";
export const ACTIVE_STEP_DECRAMENT = "ACTIVE_STEP_DECRAMENT";
export const ACTIVE_STEP_RESET = "ACTIVE_STEP_RESET";
export const SET_FORM_FIELDS = "SET_FORM_FIELDS";

export const SET_THEME_TYPE = "SET_THEME_TYPE";
export const SET_LANGUAGE_APP = "SET_LANGUAGE_APP";

// Registration
export const SEND_REGISTRATION_DATA = "SEND_REGISTRATION_DATA";
export const SEND_REGISTRATION_DATA_PENDING = "SEND_REGISTRATION_DATA_PENDING";
export const SEND_REGISTRATION_DATA_SUCCESS = "SEND_REGISTRATION_DATA_SUCCESS";
export const SEND_REGISTRATION_DATA_ERROR = "SEND_REGISTRATION_DATA_ERROR";
export const CHECK_EXIST_EMAIL_AND_SEND_DATA =
  "CHECK_EXIST_EMAIL_AND_SEND_DATA";
export const CHECK_EXIST_EMAIL_AND_SEND_DATA_PENDING =
  "CHECK_EXIST_EMAIL_AND_SEND_DATA_PENDING";
export const CHECK_EXIST_EMAIL_AND_SEND_DATA_SUCCESS =
  "CHECK_EXIST_EMAIL_AND_SEND_DATA_SUCCESS";

export const CHECK_EXIST_EMAIL_AND_SEND_DATA_ERROR =
  "CHECK_EXIST_EMAIL_AND_SEND_DATA_ERROR";

// LOGIN
export const SEND_LOGIN_DATA = "SEND_LOGIN_DATA";
export const SEND_LOGIN_DATA_PENDING = "SEND_LOGIN_DATA_PENDING";
export const SEND_LOGIN_DATA_SUCCESS = "SEND_LOGIN_DATA_SUCCESS";
export const SEND_LOGIN_DATA_ERROR = "SEND_LOGIN_DATA_ERROR";
export const CURRENT_USER_INFO_PENDING = "CURRENT_USER_INFO_PENDING";
export const CURRENT_USER_INFO_SUCCESS = "CURRENT_USER_INFO_SUCCESS";
export const CURRENT_USER_INFO_ERROR = "CURRENT_USER_INFO_ERROR";

// logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// delete user
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

// Get rooms
export const GET_ROOMS_PENDING = "GET_ROOMS_PENDING";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_ERROR = "GET_ROOMS_ERROR";
