// REGISTRATION FORM CONSTANTS
export const ACTIVE_STEP_INCREMENT = "ACTIVE_STEP_INCREMENT";
export const ACTIVE_STEP_DECRAMENT = "ACTIVE_STEP_DECRAMENT";
export const ACTIVE_STEP_RESET = "ACTIVE_STEP_RESET";
export const SET_FORM_FIELDS = "SET_FORM_FIELDS";

export const SET_THEME_TYPE = "SET_THEME_TYPE";
export const SET_LANGUAGE_APP = "SET_LANGUAGE_APP";

// AXIOS
export const SEND_DATA = "SEND_DATA";
export const SEND_DATA_PENDING = "SEND_DATA_PENDING";
export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS";
export const SEND_DATA_ERROR = "SEND_DATA_ERROR";
